// @generated by Chat-GPT

import { attemptToParseColorValueArray } from '@src/options/color-value-array.ts';

describe('attemptToParseColorValueArray', () => {
  const validColorArray = JSON.stringify([
    'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k',
  ]);

  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('returns false if input is not bracketed', () => {
    const result = attemptToParseColorValueArray('"a","b","c"');
    expect(result).toBe(false);
  });

  it('parses valid color array successfully', () => {
    const result = attemptToParseColorValueArray(validColorArray);
    // validation is not implemented, so this test only asserts that parsing passes
    expect(result).toEqual(expect.any(Array));
    expect(result).toHaveLength(11);
  });

  it('repairs single quotes and parses', () => {
    const input = "['a','b','c','d','e','f','g','h','i','j','k']";
    const result = attemptToParseColorValueArray(input);
    expect(result).toEqual(expect.any(Array));
    expect(result).toHaveLength(11);
  });

  it('repairs semicolon-separated items', () => {
    const input = '["a";"b";"c";"d";"e";"f";"g";"h";"i";"j";"k"]';
    const result = attemptToParseColorValueArray(input);
    expect(result).toEqual(expect.any(Array));
    expect(result).toHaveLength(11);
  });

  it('repairs space-separated values with no quotes', () => {
    const input = '[a b c d e f g h i j k]';
    const result = attemptToParseColorValueArray(input);
    expect(result).toEqual(expect.any(Array));
    expect(result).toHaveLength(11);
  });

  it('repairs comma-separated values with no quotes', () => {
    const input = '[a,b,c,d,e,f,g,h,i,j,k]';
    const result = attemptToParseColorValueArray(input);
    expect(result).toEqual(expect.any(Array));
    expect(result).toHaveLength(11);
  });

  it('removes trailing commas and repairs', () => {
    const input = '["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", ]';
    const result = attemptToParseColorValueArray(input);
    expect(result).toEqual(expect.any(Array));
    expect(result).toHaveLength(11);
  });

  it('removes empty strings and repairs', () => {
    const input = '["a", "b", "", "c", "d", "e", "f", "g", "h", "i", "j", "k"]';
    const result = attemptToParseColorValueArray(input);
    expect(result).toEqual(expect.any(Array));
    expect(result).toHaveLength(11);
  });

  it('rethrows if repair still fails with ColorValueArraySyntaxException', () => {
    const broken = '[123]';
    expect(() => {
      attemptToParseColorValueArray(broken);
    }).toThrow();
  });
});
